//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenWeather.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenWeather.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAKH,56.9333333333333,-154.183333333333,14,US,AK,AKHIOK
        ///PAUT,54.15,-165.6,25,US,AK,AKUTAN
        ///PAFM,67.1,-157.85,88,US,AK,AMBLER
        ///PAKP,68.1333333333333,-151.733333333333,642,US,AK,ANAKTUVUK PASS
        ///PANC,61.1666666666667,-150.016666666667,38,US,AK,ANCHORAGE INTL
        ///PAFC,61.1666666666667,-150.033333333333,48,US,AK,ANCHORAGE/WFO
        ///PAHG,60.7333333333333,-151.35,74,US,AK,ANCHORAG/NIKISKI
        ///PALH,61.1833333333333,-149.966666666667,22,US,AK,ANCHORAGE/LAKE H
        ///PZAN,61.1666666666667,-149.983333333333,22,US,AK,ANCHORAGE/ARTCC
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string official_stations {
            get {
                return ResourceManager.GetString("official_stations", resourceCulture);
            }
        }
    }
}
